<?php
/** @var array $summary */
/** @var array $breakdown */
/** @var string $from */
/** @var string $to */
?>
<table border="1">
    <tr>
        <th colspan="3" style="background-color: #f2f2f2; font-size: 14pt;">YARD FINANCIAL PERFORMANCE SUMMARY</th>
    </tr>
    <tr>
        <th colspan="3">Period: <?= $from ?> to <?= $to ?></th>
    </tr>
    <tr><td colspan="3"></td></tr>
    
    <!-- METRICS -->
    <tr style="background-color: #d1ffd1;">
        <td colspan="2"><b>TOTAL OPERATIONAL COLLECTIONS (INCOME)</b></td>
        <td style="text-align: right;"><b>KES <?= number_format($summary['income'], 2) ?></b></td>
    </tr>
    <tr style="background-color: #ffd1d1;">
        <td colspan="2"><b>TOTAL YARD EXPENDITURE (OUTGOINGS)</b></td>
        <td style="text-align: right;"><b>KES <?= number_format($summary['expenses'], 2) ?></b></td>
    </tr>
    <tr style="background-color: #d1e4ff;">
        <td colspan="2"><b>ESTIMATED NET OPERATING PROFIT</b></td>
        <td style="text-align: right;"><b>KES <?= number_format($summary['profit'], 2) ?></b></td>
    </tr>
    
    <tr><td colspan="3"></td></tr>
    
    <!-- CATEGORIES -->
    <tr style="background-color: #f2f2f2;">
        <th>Expense Category</th>
        <th colspan="2">Amount Incurred (KES)</th>
    </tr>
    <?php foreach ($breakdown as $item): ?>
    <tr>
        <td><?= $item['category_name'] ?></td>
        <td colspan="2" style="text-align: right;"><?= number_format($item['total_amount'], 2) ?></td>
    </tr>
    <?php endforeach; ?>
    
    <tr><td colspan="3"></td></tr>
    <tr style="font-size: 8pt; color: #555;">
        <td colspan="3">This report was automatically generated by CYMIS on <?= date('d M Y H:i:s') ?>.</td>
    </tr>
</table>
