<?php
use yii\helpers\Html;
use yii\grid\GridView;

/* @var $dataProvider yii\data\ActiveDataProvider */
/* @var $settings admin\models\static\General */
/* @var $title string */
/* @var $columns array */
/* @var $isExcel bool */

// Logo Logic (Only for Print/PDF)
$logoUrl = null;
if (!$isExcel && $settings->site_logo) {
    $logoUrl = Yii::getAlias('@web') . '/' . $settings->site_logo;
}

// Excel-safe styling
$border = $isExcel ? 'border="1"' : 'class="report-table"';
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title><?= Html::encode($title) ?></title>
    <?php if (!$isExcel): ?>
    <style>
        body { font-family: 'Helvetica', sans-serif; font-size: 12px; padding: 20px; color: #333; }
        .header { text-align: center; margin-bottom: 30px; border-bottom: 2px solid #444; padding-bottom: 10px; }
        h1 { margin: 0; font-size: 20px; text-transform: uppercase; color: #004085; font-weight: bold; }
        .company-info { font-size: 11px; margin-top: 5px; line-height: 1.4; }
        .report-title { font-size: 16px; font-weight: bold; margin-top: 15px; text-decoration: underline; }
        
        /* Table */
        .report-table { width: 100%; border-collapse: collapse; margin-top: 10px; }
        .report-table th { background: #f2f2f2; text-align: left; padding: 8px; border: 1px solid #ccc; font-size: 11px; font-weight: bold; text-transform: uppercase; }
        .report-table td { padding: 8px; border: 1px solid #ccc; font-size: 11px; }
        
        /* Print Button */
        .no-print { text-align: right; margin-bottom: 20px; }
        @media print { .no-print { display: none; } }
    </style>
    <?php endif; ?>
</head>
<body>

    <?php if (!$isExcel): ?>
    <div class="no-print">
        <button onclick="window.print()" style="padding: 10px 20px; background: #006D44; color: white; border: none; cursor: pointer; border-radius: 4px; font-weight: bold;">
            🖨️ Print Report
        </button>
    </div>
    <?php endif; ?>

    <!-- REPORT HEADER -->
    <div class="header" style="text-align: center; margin-bottom: 20px;">
        <?php if ($logoUrl): ?>
            <img src="<?= $logoUrl ?>" style="max-height: 80px; max-width: 150px;">
        <?php endif; ?>
        
        <h1 style="font-size: 18px; font-weight: bold; margin: 5px 0;"><?= Html::encode($settings->organization_name) ?></h1>
        
        <?php if (!$isExcel): ?>
        <div class="company-info">
            <?= Html::encode($settings->physical_address) ?><br>
            Tel: <?= Html::encode($settings->primary_mobile_number) ?> | Email: <?= Html::encode($settings->email_address) ?>
        </div>
        <?php endif; ?>

        <div class="report-title" style="font-size: 14px; font-weight: bold; margin-top: 15px; text-decoration: underline;">
            <?= Html::encode($title) ?>
        </div>
        <div style="font-size: 11px; color: #666; margin-top: 5px;">
            Generated on: <?= date('d M Y, h:i A') ?>
        </div>
    </div>

    <!-- DATA TABLE -->
    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'summary' => '', 
        'columns' => $columns, 
        'tableOptions' => $isExcel ? ['border' => '1'] : ['class' => 'report-table'],
        'emptyText' => 'No records found.',
        'emptyTextOptions' => ['style' => 'text-align:center; padding:20px; color:#777;'],
    ]); ?>

    <div class="footer" style="margin-top: 30px; font-size: 10px; color: #777; text-align: center;">
        Generated by: <?= Yii::$app->user->identity->username ?>
    </div>

</body>
</html>